sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - gh-pages
    - /.*/

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test --watch=false --code-coverage
  - ng e2e
